name: DB update stocks

on:
  schedule:
    - cron: '0 13 * * 1-5'  # every 2 hours 9AM-4PM EST → adjust as needed
  workflow_dispatch:
  
permissions:
  contents: write   # allow push

jobs:
  update-db:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas requests

      - name: Run update script
        env:
          FMP_API_KEY: ${{ secrets.FMP_API_KEY }}
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}      
        run: |
          python db_scripts/grade_change_db.py 2025-10-03

      - name: Commit DB changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add data/stocks.db
          git commit -m "Update database [skip ci]" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
