name: DB update stocks

on:
  schedule:
    - cron: '0 13 * * 1-5'  # every 2 hours 9AM-4PM EST → adjust as needed
  workflow_dispatch:
  
permissions:
  contents: write   # allow push

jobs:
  update-db:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas requests

      - name: Download previous DB
        uses: actions/download-artifact@v3
        with:
          name: stocks-db
          path: data/
        continue-on-error: true   # first run m
      
      - name: Run update script
        env:
          FMP_API_KEY: ${{ secrets.FMP_API_KEY }}
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}      
        run: |
          python db_scripts/grade_change_db.py

      - name: Upload DB artifact
        uses: actions/upload-artifact@v3
        with:
          name: stocks-db
          path: data/stocks.db
