name: CSV update stocks

on:
  schedule:
    - cron: '0 13 * * 1-5'  # every weekday at 9AM EST
  workflow_dispatch:

permissions:
  contents: write   # ✅ allow push back to repo

jobs:
  update-csv:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas requests openpyxl

      - name: Run update script
        env:
          FMP_API_KEY: ${{ secrets.FMP_API_KEY }}
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: |
          python db_scripts/grade_change_db.py
          python db_scripts/penny_losers_gainers.py

      - name: Commit and push CSV
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add data/grades_updates.csv
          git add data/grades_updates.xlsx
          git commit -m "Update grades CSV [skip ci]" || echo "No changes to commit"
          git push
