name: Daily Top Price changes

on:
  schedule:
    - cron: '0 13 * * *'  # Runs daily at 13:00 UTC (adjust as needed)
  workflow_dispatch:       # Allows manual run from GitHub UI

jobs:
  run-daily-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Python script
        env:
          FMP_API_KEY: ${{ secrets.FMP_API_KEY }}
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: python working_fmp.py
